steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/voteup-495218/voteup/voteup-api', '-f', 'apps/api/Dockerfile', '.']
images:
  - 'us-central1-docker.pkg.dev/voteup-495218/voteup/voteup-api'
