steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/voteup-fb/voteup/voteup-web', '-f', 'apps/web/Dockerfile', '.']
images:
  - 'us-central1-docker.pkg.dev/voteup-fb/voteup/voteup-web'
